lab-data: debugging: ebpf: silence warning with BPF_KPROBE()
Using BPF_KPROBE() implies having unused function parameters. Silence them.

Fixes:

    trace_programs.bpf.c:14:5: error: unused parameter 'ctx' [-Werror,-Wunused-parameter]
    int BPF_KPROBE(trace_execve, char *pathname, char *argv[], char *envp[])
        ^
    /usr/include/bpf/bpf_tracing.h:433:28: note: expanded from macro 'BPF_KPROBE'
    ____##name(struct pt_regs *ctx, ##args)
                               ^
    trace_programs.bpf.c:14:52: error: unused parameter 'argv' [-Werror,-Wunused-parameter]
    int BPF_KPROBE(trace_execve, char *pathname, char *argv[], char *envp[])
                                                       ^
    trace_programs.bpf.c:14:66: error: unused parameter 'envp' [-Werror,-Wunused-parameter]
    int BPF_KPROBE(trace_execve, char *pathname, char *argv[], char *envp[])
                                                                     ^

Signed-off-by: Luca Ceresoli <luca.ceresoli@bootlin.com>