slides/sysdev-build-systems: yocto: STM32MP1 failed to build
with kirkstone branches, the compilation failed because meta-st-stm32mp
was using a recipe gcc-11.3 whereas openembedded-core switched to
gcc-11.4

It fails with:
MACHINE=stm32mp1 bitbake core-image-minimal
Loading cache: 100% |      | ETA:  --:--:--
Loaded 0 entries from dependency cache.
Parsing recipes: 100% |######| Time: 0:00:19
Parsing of 2241 .bb files complete (0 cached, 2241 parsed). 3632 targets, 179 skipped, 0 masked, 0 errors.
ERROR: No recipes in default available for:
  /home/richard/training/embedded_linux_system_development/yocto/meta-st-stm32mp/recipes-devtools/gcc/gcc-source_11.3.bbappend

Summary: There was 1 ERROR message, returning a non-zero exit code.

Even if we're supposed to follow the labs rather than the slides, it's
always better to have something that works.

Signed-off-by: Richard Genoud <richard.genoud@bootlin.com>