training: slides: debugging-application-tracing: fix LD_PRELOAD example
Fix the example so it is usable out of the box (tested on Ubuntu 22.04).

Fixes build error:

  my_lib.c:3:1: error: unknown type name ‘ssize_t’; did you mean ‘size_t’?

and runtime error:

  ERROR: ld.so: object 'my_lib.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

Signed-off-by: Luca Ceresoli <luca.ceresoli@bootlin.com>