yocto: lab6: upgrade to kirkstone (stm32 boards)
Update the required MACHINE configuration variables, taking the minimum
required from the ST layer.

Let's stop having a shared feature list because for ST boards we now need
the m4copro MACHINE_FEATURE to avoid this nasty error:

  ERROR: st-image-userfs-1.0-r0 do_rootfs: Could not invoke dnf. Command '[...]' returned 1:
  DNF version: 4.11.1
  cachedir: .../tmp/work/bootlinlabs-poky-linux-gnueabi/st-image-userfs/1.0-r0/rootfs/var/cache/dnf
  Added oe-repo repo from .../tmp/work/bootlinlabs-poky-linux-gnueabi/st-image-userfs/1.0-r0/oe-rootfs-repo
  User-Agent: falling back to 'libdnf': could not detect OS or basearch
  repo: using cache for: oe-repo
  oe-repo: using metadata from Tue 12 Jul 2022 03:07:21 PM UTC.
  --> Starting dependency resolution
  --> Finished dependency resolution
  Error:
   Problem: conflicting requests
    - nothing provides /bin/sh needed by linux-examples-stm32mp1-userfs-5.4+0+8e1c0b246c-r0.bootlinlabs
  (try to add '--skip-broken' to skip uninstallable packages)

Signed-off-by: Luca Ceresoli <luca.ceresoli@bootlin.com>